// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plugins.Datastore.SQL;

#nullable disable

namespace Plugins.Datastore.SQL.Migrations
{
    [DbContext(typeof(MarketContext))]
    partial class MarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devices and gadgets.",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fiction and non-fiction books.",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Men's and women's apparel.",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Appliances for home use.",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sports equipment and gear.",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Children's toys and games.",
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Beauty products and cosmetics.",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Car and motorcycle accessories.",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Health and wellness products.",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Food and daily essentials.",
                            Name = "Grocery"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 999.99000000000001,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 699.99000000000001,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Headphones",
                            Price = 199.99000000000001,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "C# Programming",
                            Price = 39.990000000000002,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Fiction Novel",
                            Price = 15.99,
                            Quantity = 75
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "T-Shirt",
                            Price = 19.989999999999998,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Jeans",
                            Price = 49.990000000000002,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Blender",
                            Price = 89.989999999999995,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Tennis Racket",
                            Price = 79.989999999999995,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Name = "Action Figure",
                            Price = 24.989999999999998,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("CoreBusiness.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtyBefore")
                        .HasColumnType("int");

                    b.Property<int>("SoldQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.HasOne("CoreBusiness.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
